# Generated by Django 4.0.4 on 2022-05-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloguser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(default='images/python.jpeg', upload_to='media'),
        ),
    ]
