# Generated by Django 4.0.4 on 2022-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_like_alter_post_view_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать на сайте'),
        ),
    ]
